import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

const soulmaze = localFont({
    src: "./fonts/soulmaze.otf",
    style: "normal",
    weight: "400",
});

export const metadata: Metadata = {
    title: "The Threesome Project",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className={soulmaze.className}>{children}</body>
        </html>
    );
}
